[김규리] 15주차 2146번 과제 제출합니다.
kth990303/BojCodingTestStudy pull request #100
Opened 2022-06-26 02:45 UTC by everglow03

2022-06-26 12:26 UTC, donghoony requested changes
`NameError` 해결방안을 올려드려요

2022-06-26 12:26 UTC, donghoony commented on 15주차/2146/2146_python_gyuri.py
> +flag = [0 for i in range(len(vertices))]
`vertices`가 정의돼있지 않습니다

2022-06-28 00:07 UTC, rlawngP91 approved these changes

2022-06-28 00:07 UTC, rlawngP91 commented on 15주차/2146/2146_python_gyuri.py
> +
8번째줄을 여기에다 넣는건 어떨까요?😄

2022-06-28 00:07 UTC, rlawngP91 commented on 15주차/2146/2146_python_gyuri.py
> +    return lands
쭉 읽고 이해해봤을때 동훈님이 말씀하신거 빼고는 크게 오류가 보이지는 않습니다~! 노력많이 한게 느껴져요☺️

2022-06-29 14:50 UTC, closed without merging