최범준] 15주차 과제제출
kth990303/BojCodingTestStudy pull request #102
Opened 2022-06-26 04:17 UTC by ChoiBeomJun99

2022-06-26 12:15 UTC, donghoony requested changes
조금만 더 생각해보면 효율성에서도 통과하실 수 있을 것 같아요! 수고하셨습니다~!

2022-06-26 12:15 UTC, donghoony commented on 15주차/(P)72412_python_최범준.py
> +        print("------------------------")
프로그래머스에서는 상관없겠지만, 다른 플랫폼에서는 불필요한 출력으로 인한 오답처리를 받을 수 있어요!

2022-06-26 12:15 UTC, donghoony commented on 15주차/(P)72412_python_최범준.py
> +                                answer_count += 1
해당 코드는 O(NQ)로 시간초과를 받습니다. NQ를 O(QlogN)으로 낮추면 정답을 바꿀 수 있습니다. 모든 상태에 대한 배열을 만들어 두고, 배열을 정렬하는 데 NlogN이 걸립니다. 정렬된 배열에서는 이분 탐색을 활용할 수 있고, 이분 탐색은 한 번에 logN의 연산을 필요로 해요.

2022-06-26 12:15 UTC, donghoony commented on 15주차/(P)72412_python_최범준.py
> +    for query_tmp in query :
쿼리의 개수가 100,000개라서 해당 부분에서도 꽤 많은 시간을 빼앗길 수 있습니다. query를 수정하지 않고, 아래에서 각 쿼리를 split한 뒤에 0, 2, 4, 6, 7번째 인덱스에 접근하면 원하는 문자열을 가져올 수 있습니다

2022-06-26 14:55 UTC, amykim928 requested changes
뒷부분을 수정하면 좋을 거 같아 request changes로 하겠습니다! 수고하셨습니다😊

2022-06-26 14:55 UTC, amykim928 commented on 15주차/(P)72412/(P)72412_python_최범준.py
> +
문자열은 replace 함수를 통해 변경할 수 있기도 합니다:)

2022-06-26 14:55 UTC, amykim928 commented on 15주차/(P)72412/(P)72412_python_최범준.py
> +
이 코드는 효율성이 좋지 않아서 이분 탐색(bisect)을 통해 구현해보세요!

2022-06-27 05:33 UTC, riroan commented on 15주차/(P)72412/(P)72412_python_최범준.py
> +            tmp_app.append(split_query[i])
for 문이 0부터 시작하는 경우 생략할 수 있습니다.
```
for i in range(3): # for i in range(0, 3):
```

2022-06-27 05:33 UTC, riroan commented on 15주차/(P)72412/(P)72412_python_최범준.py
> +                                answer_count += 1
float을 안거쳐도 될 것 같아요.

2022-06-29 14:50 UTC, closed without merging