[류동형] 3주차 14500 과제제출
kth990303/BojCodingTestStudy pull request #11
Opened 2022-03-26 08:45 UTC by Ryu-DongHyeong

이게 된건가요?

2022-03-26 15:02 UTC, kth990303 commented on 3주차/14500/14500_cpp_류동형.cpp
> +    {{0, 0}, {1, 0}, {2, 0}, {3, 0}}, //���η� ����
{0, 0}은 어차피 defalut 값이네요 :)
크게 중요하지 않지만, 타자치는데 걸리는 시간을 더 줄일 수 있을 거 같네요

2022-03-26 15:02 UTC, kth990303 commented on 3주차/14500/14500_cpp_류동형.cpp
> +    {{0, 0}, {1, 0}, {2, 0}, {3, 0}}, //���η� ����
추가로, 이 경우를 고려하는데 시간이 오래 걸리시진 않으셨나요?

2022-03-26 15:04 UTC, kth990303 commented on 3주차/14500/14500_cpp_류동형.cpp
> +    cout << answer;
전역변수로 경우의 수를 잘 처리해주셔서 시간복잡도 상으로도 깔끔하고, 크게 남길 코멘트는 없네요.
잘해주셨습니다 👍 
다만, 11~29번째 라인의 경우의 수를 구해주느라 시간이 오래 걸리시진 않으셨나요?
다른 방법도 존재합니다! (힌트: recursion)

2022-03-26 15:09 UTC, kth990303 requested changes
git 관리 어려우셨을텐데 수고 많으셨습니다~
전체 경우를 전역으로 체크하셨을텐데, 꽤나 오랜 시간이 걸리셨을 거 같아요!
정말 잘 풀어주셨지만! 다른 방법도 존재하며, 현재 방법에서 더 최적화도 가능할 거 같으니 여력이 되산다면 반영해서 다시 리뷰요청 드리면 좋을 것 같습니다 :)
화이팅! 🥇

2022-03-26 16:58 UTC, donghoony commented on 3주차/14500/14500_cpp_류동형.cpp
> +    {{0, 0}, {1, -1}, {1, 0}, {2, 0}},
Casework 끈기 👏🏼

2022-03-27 01:58 UTC, Ryu-DongHyeong commented on 3주차/14500/14500_cpp_류동형.cpp
> +    {{0, 0}, {1, 0}, {2, 0}, {3, 0}}, //���η� ����
종이에 적어서 하니 엄청 오래걸리지는 않았습니다!

2022-03-27 01:59 UTC, Ryu-DongHyeong commented on 3주차/14500/14500_cpp_류동형.cpp
> +    cout << answer;
재귀사용해서도 한번 해결해보겠습니다! 감사합니다

2022-03-27 02:03 UTC, Ryu-DongHyeong commented on 3주차/14500/14500_cpp_류동형.cpp
> +    cout << answer;
오,,재귀사용해서하면 어케해서든 주어진 모양만 나오는 문제였군요 저는 저 다른 그림도 그려질줄 알았습니다

2022-03-27 07:27 UTC, kth990303 approved these changes
지금 코드도 충분히 괜찮아서 approve 상태로 변경할게요~

2022-03-27 15:40 UTC, merged