12100 jy
kth990303/BojCodingTestStudy pull request #16
Opened 2022-03-26 12:20 UTC by gamjalee

정답 과제입니다 헤헷 헤헤

2022-03-26 14:33 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +    for (int k = 1; k <= N; k++) {
memset, fill에 대해 공부해보시면 좋을 거 같아요 :)
이에 대한 성능도 추가로 확인해보시면 어떨까요? 😄

2022-03-26 15:19 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +            if (board[i][j] != 0 ) {
`board[i][j] != 0`.equals`!board[i][j]`

스타일 차이이므로 꼭 반영할 필요는 없습니다.

2022-03-26 15:19 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if(tmp == 0){tmp = board[i][j];//0�̰� �񱳰� ��� ��
`if(!tmp){tmp=board[i][j];return;}` 

스타일 차이이므로 꼭 반영할 필요는 없습니다.

2022-03-26 15:34 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +#include <stdlib.h>
stdlib.h는 c언어 헤더파일인데 추가해준 이유가 있을까요?

2022-03-26 15:37 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +                    board[i][k] = tmp; visit[k] = true; break;
`visit[k]=true;`를 해주는 이유가 있나요?

2022-03-26 15:45 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +
M_temp는 어떤 이유로 만든걸까요?
`int M_temp[21][21]={0};`와 같이 0으로 초기화했던 것처럼, 그냥 `board`를 0으로 초기화해주면 되지 않나요?
M_temp가 따로 다른 함수에서 쓰이는 용도도 아닌 것 같아서 궁금해서 여쭤봅니다 ㅎㅎ

2022-03-26 15:54 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +    return 0;
단일 파일이면 `return 0;` 없어도 작동되긴 해요!

2022-03-26 16:02 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +                        for (int k = 1; k <= N; k++) {
비교값 같을 때, 같지 않을 때 구분 👍

2022-03-26 16:03 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if (visit[k] == false) {
for문을 안 돌고 처리할 수도 있겠네요!
다만, 이 문제에선 성능에 크게 영향을 미치진 않을 거 같네요 😄

2022-03-26 16:05 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +    }
`init_visit()` 없이 그냥 위 for문에서 `visit[k]=false;`처리로 visit배열을 초기화해줄 수 있겠네요

2022-03-26 16:06 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +    }
잘하셨어요! 참고로 그냥 답 출력하고 exit(0)으로 바로 끝내도 좋습니다 💯

2022-03-26 16:06 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +    cin.tie(0);
c++ / c 연결 끊음으로써 성능 향상 👍

2022-03-26 16:06 UTC, kth990303 approved these changes
브루트포스로 잘 풀어주셨네요 :)
웬만해선 코멘트 좀 빡세게 남기려 했는데, 지금 봤을 땐 크게 남길 게 없어보이네요.
전체적으로 봤을 때, 깔끔하게 잘 풀어주셨어요! `queue`를 이용하면 더 깔끔하게 처리할 수 있을 것 같네요.

동형님께서 남기실 부분이 있으면 추가로 피드백해주시고 없으면 머지해줘도 될 것 같습니다👍

2022-03-27 02:06 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +#include <stdlib.h>
문제 풀때마다 기본 포멧(헤더파일, 메인 함수에 ios_base::sync_with_stdio(0); cin.tie(0);)
를 복붙하는데 잘못 섞여들어간것 같네요 ㅎㅎ 감사합니다! 다음 문제풀이부터는 복붙 최대한 쓰지 않고 풀려고 노력해보겠습니다!

2022-03-27 02:13 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +
M_temp는 블록을 이동시켰을 때 그 게임판의 상태를 저장하기 위해 쓰는 지역변수입니다! board는 게임판의 초기 상태를 저장하는 전역변수입니다. move() 함수가 백트래킹, 재귀에 쓰이는 함수이다 보니 블록을 이동시킬 때마다 board에 저장하면 정상적으로 함수가 동작되지 않을 것 같았습니다. 백트래킹이 익숙하지 않아 이 방법을 썼는데 더 좋은 풀이방법 알려주신다면 감사하겠습니다! :)

2022-03-27 02:14 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +    return 0;
몰랐네요,,, 감사합니다! ps 초보에게 정말 귀한 코멘트에요..

2022-03-27 02:14 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +    }
코드가 완전히 간단해지네요 감사합니다!

2022-03-27 02:17 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if (visit[k] == false) {
for문을 안 돌고 처리하는 방법은 자료구조나 다른 알고리즘 쪽은 생각이 안 나네요ㅜㅜ.. 25, 32, 42번에 같은 for문이 나오는데 이 for문에 몰아넣는 방법밖에 떠오르지 않습니다. 조금 더 자세히 알려주실 수 있을까요?

2022-03-27 02:18 UTC, gamjalee commented
감사합니다!

2022-03-27 02:34 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +            if (visit[k] == false) { board[i][k] =0;  }
이 for문도 위 for문이 남아있는다면 위에서 한번에 처리해줌으로써 없앨 수 있겠네요 :)

2022-03-27 02:36 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if (visit[k] == false) {
현재 42~45번째 라인에선 어차피 1번 index부터 탐색해서 방문하지 않은 가장 작은 index에만 로직을 실행하고 break로 for문을 벗어나고 있네요!
가장 작은 index를 변수로 가지고 있는다면 for문을 돌지 않고 바로 처리할 수 있겠네요 😄

2022-03-27 02:38 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if (visit[k] == false) {
확인했습니다! 완전 이해가 가네요 감사합니다!

2022-03-27 02:44 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +
그렇군요~ 그러면 `M_temp`가 필요하겠네요.

2022-03-27 02:47 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if (tmp == 0) {
`up()`함수와 `left()`함수는 i, j 위치만 바뀌고 나머지 로직은 완전히 똑같은데,
중복을 줄일 수 있을까요? 조금 어렵긴 하지만 도전해보시는 것도 좋을 거 같네요 ㅎㅎ

만약 더 줄인다면 `up`, `down`, `left`, `right`를 전부 하나의 함수로도 묶을 수도 있겠는데, 이건 좀 더 어려우니 가능하다면 반영해보시면 좋을 거 같아요! 반영하지 않고 참고만 하셔도 좋습니다 :)

2022-03-27 02:48 UTC, kth990303 requested changes
추가질문 확인했습니다 :)
원래는 머지하려 했었는데, 조금 다듬어서 push하면 더 예쁜 코드가 나올 수 있을 거 같아 수정요청 드릴게요~ 수고하셨어요!

2022-03-27 03:30 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +                if (tmp == 0) {
넵넵 ㅎㅎ 우선 이 위에 코멘트까지 반영한 버전 push하고 13번 pr 확인 후 도전해보겠습니다!
감사합니다 👍

2022-03-28 07:48 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +    cout << maxx; exit(0);
`exit(0);`도 없어도 돼요~~
오히려 `exit(0);` 보단 `return 0;`이 나은 것 같아요

2022-03-28 07:49 UTC, kth990303 commented on 3주차/12100/12100_cpp_이지영.cpp
> +        memset(visit, false, sizeof(visit));
`memset`은 사실 `for문`보단 성능이 조금 떨어집니다.
이 부분 감안해서 편의성 vs 성능 중 더 괜찮다고 생각되는 것을 선택해주시면 좋을 듯해요~~

2022-03-28 07:49 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +    cout << maxx; exit(0);
헉 그렇군요 참고하겠습니다! 👍 👍

2022-03-28 07:50 UTC, kth990303 approved these changes
수고 많으셨어요~!
몇 가지 코멘트 남겨드렸는데 확인해주세요 :)
이만 머지할게요~

2022-03-28 07:50 UTC, merged

2022-03-28 07:51 UTC, gamjalee commented on 3주차/12100/12100_cpp_이지영.cpp
> +        memset(visit, false, sizeof(visit));
감사합니다! 정말 많이 배우네요 👍