[류동형] 20061 과제 제출합니다
kth990303/BojCodingTestStudy pull request #22
Opened 2022-03-30 14:35 UTC by Ryu-DongHyeong

2022-03-31 02:36 UTC, kth990303 requested changes
쉽지 않았을텐데 수고많으셨어요~!
코드량은 많지만 전반적으로 깔끔하고 가독성이 좋네요 👍 

몇가지 코멘트 남겨드렸으니 리팩토링해보시면 좋을 듯해요!

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +int count_block = 0;
```suggestion
int count_block;
```
전역변수는 디폴트 값이 0입니다.

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +        if (blue[x][i] == 1) {
0 또는 1 값만 들어가는 거 같네요 ㅎㅎ blue[x][i]라고만 해도 괜찮겠네요. 스타일 차이이긴 하니까 넘어가셔도 됩니다

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            }
그냥 count_block+=blue[i][j]; count_block+=green[j][i];로 해도 되겠네요!

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            blue[0][0] = 0; blue[1][0] = 0; blue[2][0] = 0; blue[3][0] = 0;//������ ä���ֱ�
34~37번째 라인 조금 노가다스러운데, 한번 고쳐볼까요?

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            move_green();
어차피 move_blue(), move_green()은 어떤 경우든 실행되네요!
다만, c==1 케이스를 만들어두고, 2, 3인 경우는 c==1 케이스를 복사하시다보니 그렇게 된 것 같아서 크게 불편하진 않으셨을 거 같지만! 혹시나 해서 코멘트 남겨요

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            }i++;
위 for문에서 i를 하나씩 줄여주고 있는데, i++; 은 왜 있는건가요? i가 같은 값을 유지해야되는건가요?

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            return i-1;
0-index와 1-index가 섞여있어서 코드가 조금 복잡해진 것 같은데요.
하나로 통일하면 좋을 듯해요~!

2022-03-31 02:36 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            green[green_idx][y + 1] = 1;
꼼꼼한 index 체크 👍

2022-03-31 02:45 UTC, donghoony commented on 4주차/20061/20061_cpp_류동형.cpp
> +            return i-1;
가장 위 블럭 윗블럭에 놓아야 하는거라 0-based 아닌가요 ?

2022-03-31 03:02 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            return i-1;
그러네요 ㅎㅎ 제가 로직을 조금 잘못 이해했네요!

2022-03-31 03:49 UTC, Ryu-DongHyeong commented on 4주차/20061/20061_cpp_류동형.cpp
> +int count_block = 0;
감사합니다!

2022-03-31 03:50 UTC, Ryu-DongHyeong commented on 4주차/20061/20061_cpp_류동형.cpp
> +            }
오오,, 감사합니다!

2022-03-31 03:50 UTC, Ryu-DongHyeong commented on 4주차/20061/20061_cpp_류동형.cpp
> +            blue[0][0] = 0; blue[1][0] = 0; blue[2][0] = 0; blue[3][0] = 0;//������ ä���ֱ�
ㅋㅋㅋ알겠습니다 for문 3중 이상들가면 뭔가 변수 고민하게 되어서 저렇게 습관적으로 쓴거같습니다

2022-03-31 03:53 UTC, Ryu-DongHyeong commented on 4주차/20061/20061_cpp_류동형.cpp
> +            }i++;
아 저거때문에 3시간걸렸는데 그 만약 
 4행   o o o x
 5행   o o o x
 이렇게 되어 있는데 2칸 테트리스 내려와서
 4행   o o o o
 5행   o o o o 되면은
 5행 먼저 없애면
 
 4행    x x x x
 5행    o o o o 이렇게 되게 해주었는데
 4행이 아닌 다시 5행 검사해주게 해주기 위해 i++;해주었습니다

2022-03-31 03:54 UTC, Ryu-DongHyeong commented on 4주차/20061/20061_cpp_류동형.cpp
> +            green[green_idx][y + 1] = 1;
꼼꼼한 피드백 감사합니다

2022-03-31 05:46 UTC, kth990303 commented on 4주차/20061/20061_cpp_류동형.cpp
> +            blue[0][0] = 0; blue[1][0] = 0; blue[2][0] = 0; blue[3][0] = 0;//������ ä���ֱ�
만약 이게 개발이었으면 indent, 중복 로직 체크 등을 중점으로 리뷰했을 것 같은데,
알고리즘이다보니 정확성, 편의성, 시간을 줄이는 방법 등에 중점을 맞추고 있어서 피드백한 것 같아요 ㅎㅎ
for문을 쓰면 더 간편하고 빠르게 작성할 수 있어보이네요!

2022-04-02 00:33 UTC, gamjalee commented on 4주차/20061/20061_cpp_류동형.cpp
> +}
전반적으로 로직이 깔끔하시고 태현님이 피드백 다 남겨주셨네요..! 고생하셨습니다 👍

2022-04-03 04:13 UTC, kth990303 approved these changes

2022-04-03 17:12 UTC, merged