[노유빈] (P)17686, (P)42578 과제 제출합니다.
kth990303/BojCodingTestStudy pull request #61
Opened 2022-05-25 11:11 UTC by YOOBINNOH

[노유빈] (P)17686, (P)42578 과제 제출합니다.

2022-05-26 06:24 UTC, kth990303 commented
[해당 글](https://wooono.tistory.com/251)을 참고하여 ds_store 파일을 제거해볼까요?

2022-05-26 08:26 UTC, kth990303 requested changes
수고하셨어요~ `ds_store` 파일은 file_changes에 여전히 남아있네요 😢 
제거하기 힘들다면 넘어가셔도 좋습니다!

현재 일부 틀리는 문항에 대해서만 간단하게 코멘트 남겨드렸어요.
확인 후 공부해보시는 걸 **강력하게** 추천드리므로 changes request 상태로 남겨드려요

2022-05-26 08:26 UTC, kth990303 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +                    c[j] = t3
지금은 크게 상관없지만 시간복잡도가 어떻게 될까요?
파이썬에서 제공해주는 sort 함수와 함께 사용자 지정 조건을 설정해주어 해결하면 더 좋아보여요.

sort로 시간도 줄일 수 있고, 정확성도 높일 수 있어보여요

2022-05-26 08:26 UTC, kth990303 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +    answer = [ ]
answer 리스트를 재정의해준 이유가 있을까요?

2022-05-26 08:26 UTC, kth990303 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +                if int(b[i])>int(b[j]):
```suggestion
            elif: int(b[i])>int(b[j]):
```

2022-05-26 08:26 UTC, kth990303 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +                if int(b[i])>int(b[j]):
a[i].lower() < a[j].lower() 이면서 int(b[i])>int(b[j])인 경우는 어떻게 되나요?

추가로, 아마 이 부분을 고친다하더라도 모든 케이스가 통과되진 않을 거예요. 좀 더 고민해보세요!

2022-05-27 00:43 UTC, amykim928 reviewed
조금 더 깔끔해질 수 있는 부분은 리뷰에 적어두었어요!
틀린 문제는 리뷰 보고 다시 한 번 더 고민해보세요😊

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)42578/(P)42578_노유빈_python.py
> +    for i in range(0,len(clothes)):
0을 쓰지 않아도 0부터 시작해요! 가독성을 위해 쓴 거면 괜찮지만요ㅎㅎ

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)42578/(P)42578_노유빈_python.py
> +
이렇게 정리해도 되지만 파이썬에는 defaultdict이라는 딕셔너리 구조가 있어요!
그걸로 풀면 key는 옷 종류 value는 종류에 맞는 옷으로 구분할 수 있기도 합니다:)

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)42578/(P)42578_노유빈_python.py
> +
처음 clothes를 돌 때 종류별로 옷 개수를 세는 건 어떨까요?

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)42578/(P)42578_노유빈_python.py
> +    return answers-1
수고하셨습니다! defaultdict은 나중에도 아주 유용하게 사용할 수 있으니까 꼭 한 번 찾아보길 바라요:)

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +            if n[i][j].isdigit()!=True:
```suggestion
    for file in n:
        if not file[i].isdigit():
```
1. for문은 시작 범위를 주지 않으면 0부터 시작해요.
2. list로 변환하지 않아도 문자열 그대로 index 탐색 가능해요.
```python
x = 'abc'
for i in x:
    print(i)

'''
result:
a
b
c
'''
```
3. range를 사용하지 않고 이런 방식으로도 for문을 사용할 수 있어요!

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +        for k in range(len(list(a1)),len(list(files[i]))):
list로 변환할 필요 없어요 문자열도 가능합니다!

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +            if files[i][k].isdigit()==True:
==True을 쓰지 않아도 조건문이 참이라면 수행합니다~

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +
append를 사용하면 순서대로 리스트에 추가할 수 있어요

2022-05-27 00:43 UTC, amykim928 commented on 12주차/(P)17686/(P)17686_노유빈_python.py
> +                    c[j] = t3
sort랑 같이 lambda라는 기능도 같이 찾아보세요 여러 기준으로 정렬할 때 아주 유용해요!

2022-05-27 00:51 UTC, amykim928 requested changes
저도 몇 가지 기능은 꼭 알고 있으면 좋을 거 같아 request changes로 합니다!

2022-05-31 04:37 UTC, kth990303 approved these changes
수고하셨어요~ 리뷰 반영이 다 되진 않은 것 같네요 🥺
하지만 열심히 공부하면서 노력하신 게 보입니다 🙂
다음 주차 과제 진행을 위해 머지처리하겠습니다.

2022-06-02 03:37 UTC, merged