노유빈_15주차_(p)17649
kth990303/BojCodingTestStudy pull request #85
Opened 2022-06-25 12:33 UTC by YOOBINNOH

2022-06-25 16:16 UTC, gamjalee commented on 15주차/(P)17679/(P)17679_Python_노유빈.py
> +        for j in range(0,len(a[0])-1):
범위 체크 굿 👍

2022-06-25 16:16 UTC, gamjalee commented on 15주차/(P)17679/(P)17679_Python_노유빈.py
> +            if a[i][j]==a[i+1][j] and a[i][j]==a[i][j+1] and a[i][j]==a[i+1][j+1]:
`a[i][j]==a[i+1][j]==a[i][j+1]==a[i+1][j+1]`
이렇게 한번에 묶어주셔도 아마 돌아갈거에요!

2022-06-25 16:16 UTC, gamjalee commented on 15주차/(P)17679/(P)17679_Python_노유빈.py
> +                if a[i+1][j] == '0':
아마 이 부분에서 테스트 코드 10번 정확성이 걸린 것 같아요! 저도 틀린 문제라 같이 고민하면 좋겠습니다 :)

2022-06-25 17:29 UTC, donghoony requested changes
오랜만입니다! 리뷰 남겨드려요~!

2022-06-25 17:29 UTC, donghoony commented on 15주차/(P)17679/(P)17649_Python_노유빈.py
> +        for j in range(0,len(a[0])-1):
`range(x)`는 [0, x) 정수를 만들어내는 generate object입니다. 0을 넣지 않고 `len(a)-1`와 같이 써도 같아요

2022-06-25 17:29 UTC, donghoony commented on 15주차/(P)17679/(P)17649_Python_노유빈.py
> +            a[list[i][0]+1][list[i][1]+1]='0'
`pythonic`하게 코드를 작성할 수 있습니다!
나아가서, `list`는 리스트를 만드는 예약어이기 때문에 변수명으로 부적절해요.
```suggestion
        for i, j in list:
            a[i][j] = '0'
```

2022-06-25 17:29 UTC, donghoony commented on 15주차/(P)17679/(P)17649_Python_노유빈.py
> +        a.append(str)
주어진 board를 더이상 활용하지 않는다면, board 자체를 바꿔도 괜찮아 보입니다
`board = [list(x) for x in board]`

2022-06-25 17:29 UTC, donghoony commented on 15주차/(P)17679/(P)17649_Python_노유빈.py
> +        a=remove(a)
M*N만으로 충분히 모든 블럭이 제거됨이 보장되나요?

2022-06-25 17:39 UTC, donghoony requested changes

2022-06-25 17:39 UTC, donghoony commented on 15주차/(P)17679/(P)17649_Python_노유빈.py
> +                    a[i][j] = '0'
```
10101
01010
22101
22010
```
와 같은 경우에는 가장 윗줄이 내려오지 않습니다

2022-06-26 10:39 UTC, amykim928 requested changes
이미 두 분이 리뷰를 잘 해주셔서 중복되지 않는 선에서 작성했습니다.
리뷰 반영해서 코드 수정해주세요:)

2022-06-26 10:39 UTC, amykim928 commented on 15주차/(P)17679/(P)17679_Python_노유빈.py
> +        a.append(str)
문자열에서 리스트로 변환할 때 list(str)을 해도 가능합니다.

2022-06-26 10:39 UTC, amykim928 commented on 15주차/(P)17679/(P)17679_Python_노유빈.py
> +            if a[i][j]==a[i+1][j] and a[i][j]==a[i][j+1] and a[i][j]==a[i+1][j+1]:
이렇게 하면 네 칸이 0인 경우는 어떻게 되나요?

2022-06-28 01:51 UTC, kth990303 commented
해당 PR은 PR 제출자의 개인사정 혹은 지나치게 높은 체감난이도로 인해 admin 머지 처리되었습니다.

2022-06-28 01:51 UTC, merged