[노유빈]_15주차_2146,(P)72412
kth990303/BojCodingTestStudy pull request #87
Opened 2022-06-25 12:59 UTC by YOOBINNOH

2022-06-25 17:54 UTC, gamjalee commented on 15주차/2146/(P)72412_python_노유빈.py
> +        if a[i].isdigit()==True:
isdigit 함수 굿굿 👍

2022-06-25 17:54 UTC, gamjalee commented on 15주차/2146/(P)72412_python_노유빈.py
> +    for i in range(len(query)):
list 안에 cpp, java, backend 등을 넣어서 단순화할 수 있을 것 같아요!

2022-06-25 17:54 UTC, gamjalee commented on 15주차/2146/(P)72412_python_노유빈.py
> +            if compare(info[j],a[i])==True and score_compare(info[j],query[i])==True:
compare 함수 굿굿 👍

2022-06-25 17:54 UTC, gamjalee commented on 15주차/2146/2146_python_노유빈.py
> +# 각 섬 별 숫자를 다르게 표기하기
이 문제 어렵죠 😢  파이팅!!

2022-06-26 10:44 UTC, amykim928 requested changes
문제를 좀 더 고민하면 좋을 거 같아 request changes를 드릴게요!

2022-06-26 10:44 UTC, amykim928 commented on 15주차/2146/(P)72412_python_노유빈.py
> +            if compare(info[j],a[i])==True and score_compare(info[j],query[i])==True:
==True를 쓰지 않아도 수행할 수 있습니다!

2022-06-26 10:44 UTC, amykim928 commented on 15주차/2146/(P)72412_python_노유빈.py
> +    return ans
문제는 해결했지만 효율성에서 오류가 났으니까 하나 힌트를 드리자면.. 이진탐색을 이용해서 해결해보는 것도 좋을 거 같네요. 파이썬 bisect에 대해서 한 번 알아보세요!

2022-06-28 01:51 UTC, kth990303 commented
해당 PR은 PR 제출자의 개인사정 혹은 지나치게 높은 체감난이도로 인해 admin 머지 처리되었습니다.

2022-06-28 01:51 UTC, merged