[이지영] 15주차 (P)17679번 과제 제출합니다.
kth990303/BojCodingTestStudy pull request #88
Opened 2022-06-25 15:42 UTC by gamjalee

2022-06-26 11:40 UTC, donghoony requested changes

2022-06-26 11:40 UTC, donghoony commented on 15주차/(P)17679/17679_py_jylee.py
> +            if i+1<m and j+1<n and board[i][j] != '0' and (board[i][j] ==
`i+1<m and j+1<n` 비교 대신에 7, 8번 줄의 m, n을 `m-1, n-1`로 바꾸는게 더 가독성이 좋을 것 같습니다 !

2022-06-26 11:40 UTC, donghoony commented on 15주차/(P)17679/17679_py_jylee.py
> +            answer += len(disappear(m, n, board))
이미 `arr`에 저장돼 있으므로 `len(arr)`를 사용하면 됩니다!

2022-06-26 11:40 UTC, donghoony commented on 15주차/(P)17679/17679_py_jylee.py
> +    board = [list(i) for i in board]
이와 같은 방법을 list comprehension이라고 해요 👍🏼

2022-06-26 11:40 UTC, donghoony commented on 15주차/(P)17679/17679_py_jylee.py
> +    return list(zip(*board))
돌린 뒤 처리하고 다시 돌리기보다 더 효율적인 방법이 있을 것 같아요!

2022-06-27 04:46 UTC, gamjalee commented on 15주차/(P)17679/17679_py_jylee.py
> +    board = [list(i) for i in board]
처음 알았네요..! 감사합니다 😄

2022-06-27 04:47 UTC, gamjalee commented on 15주차/(P)17679/17679_py_jylee.py
> +    return list(zip(*board))
감이 잘 잡히지 않네요.. 😢  힌트 하나만 주실 수 있을까요..?

2022-06-27 08:07 UTC, donghoony commented on 15주차/(P)17679/17679_py_jylee.py
> +    return list(zip(*board))
블록을 떨어뜨리는 것은 열에 한정되니까 열마다 어떤 작업을 해 주면 좋겠죠?

2022-06-27 14:11 UTC, gamjalee commented on 15주차/(P)17679/17679_py_jylee.py
> +    return list(zip(*board))
감사합니다! 이해했습니다 😄

2022-06-29 14:48 UTC, closed without merging