[김규리] 15주차 72412번 과제 제출합니다
kth990303/BojCodingTestStudy pull request #98
Opened 2022-06-26 02:35 UTC by everglow03

2022-06-26 06:51 UTC, gamjalee commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +    return (a,b,c,d)
hash 사용하신 거 맞죠? 이런 접근방식도 좋네요! 👍

2022-06-26 06:51 UTC, gamjalee commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +            if row[j]!= "-":
문자열 slicing이네요!

2022-06-26 06:51 UTC, gamjalee commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +                    flag=False
flag 사용 굿굿 👍  고생하셨습니다!

2022-06-26 12:25 UTC, donghoony requested changes

2022-06-26 12:25 UTC, donghoony commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +    d = ((key%8)%4)%2
비트 연산을 사용하면 더 깔끔하게 나타낼 수 있을 것 같아요.
해당 비트만 빼 오고 싶다면, and 연산을 활용해 보세요!

2022-06-26 12:25 UTC, donghoony commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +                for item in hashedList[key]:
`in` 연산은 O(N)으로 꽤 느려요. 해당 문제를 효율성에서 통과하려면 O(logN)만에 찾아내야 합니다.

2022-06-26 12:25 UTC, donghoony commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +                for item in hashedList[key]:
특수한 상황(정렬 등)에서는 값을 빠르게 찾을 수 있답니다!

2022-06-27 23:57 UTC, rlawngP91 approved these changes

2022-06-27 23:57 UTC, rlawngP91 commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +
기준이 되는 문자열을 inputList에 정해놓고 info를 가지고 hash key를 만들어서 넣으신거군요!

2022-06-27 23:57 UTC, rlawngP91 commented on 15주차/(P)72412/(P)72412_python_Gyuri.py
> +        for key in keyList:
query하나마다 info로 넣어두었던 모든 key들을 탐색하도록 하셨네요! 여기서는 hash를 사용하셔서 시간이 그렇게 많이 걸리지는 않을 거 같은데 어디서가 문제일까요..ㅜㅜ 사실 저도 효율성 통과가 제대로 안됩니다😂

2022-06-29 14:50 UTC, closed without merging